name: Deploy Normal (Hybrid)

on:
  push:
    branches:
      - normal

jobs:
  trigger:
    uses: ./.github/workflows/_trigger-pipeline.yml
    with:
      prefix: hy-normal
      express: false
      source-bucket: ${{ vars.HYBRID_SOURCE_BUCKET }}
      pipeline-name: ${{ vars.HYBRID_PIPELINE_NAME }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN_HYBRID }}
