name: Deploy Normal (Hybrid)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  trigger:
    uses: ./.github/workflows/_trigger-pipeline.yml
    with:
      prefix: hy-normal
      express: false
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN_HYBRID }}
      HYBRID_SOURCE_BUCKET: ${{ secrets.HYBRID_SOURCE_BUCKET }}
      HYBRID_PIPELINE_NAME: ${{ secrets.HYBRID_PIPELINE_NAME }}
